version: '3'

tasks:
  start:
    cmds:
      - streamlit run src/styled_streamlit/main.py
    env:
      # ref: https://docs.streamlit.io/library/advanced-features/configuration
      STREAMLIT_BROWSER_GATHER_USAGE_STATS: false
  check:
    deps:
      - typecheck
      - lint
  typecheck:
    cmds:
      - uv run pyright src
  lint:
    cmds:
      - uv run ruff check src
  format:
    cmds:
      - uv run ruff format src
  test:
    cmds:
      - uv run pytest
