# https://docs.streamlit.io/develop/concepts/configuration/options
# https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[browser]
gatherUsageStats = false

[server]
port = 8501

[theme]
base = "light"
primaryColor = "#31333f"
